### PR TITLE
Adding Tabula Muris Senis datasets

### PR DESCRIPTION
**Pull request by StefaniAstrologo**

### CODE REVIEW

**Comment by LTLA** [comment]
A bit of context would help. For example, we already have a **TabulaMurisData** package - perhaps this data would find a more appropriate home there? Tagging @csoneson. 

Also, no need to use such a convoluted sequence of packages to read a H5AD file into an SCE, that's what **zellkonverter** is for.

**Comment by csoneson** [comment]
Yes, we do have a `TabulaMurisData` package in Bioconductor - and as a matter of fact, we were just in the process of submitting a `TabulaMurisSenisData` one...the repository is [here](https://github.com/fmicompbio/TabulaMurisSenisData). @StefaniAstrologo - did you already upload the data? Perhaps in any case we can move this discussion to the `TabulaMurisSenisData` package repository and see how we can best move forward/combine things.

**Comment by StefaniAstrologo** [comment]
Hi @LTLA! I have to admit I wasn't aware of the **TabulaMurisData** package. Sure we can combine things @csoneson if there is anything left that is useful :) 
About **zellkonverter**: while using this package to open the **h5ad** files it returns an empty dgMatrix. 
I tried to change the code of the function without success and then I went for this inelegant solution.

**Comment by LTLA** [comment]
I'm going to close this, assuming that you two can combine your efforts in **TabulaMurisSenis**.

A MRE on how **zellkonverter** fails would also be helpful if it is posted to the relevant repo.

**Pull request closed without merging**
