### PR TITLE
CITEseq Kotliarov 2020 dataset

### PR DESCRIPTION
**Pull request by sorjuela**
Hi @LTLA,

Would like to add another CITEseq dataset. It's publicly available as a seurat object. I'm not sure if I should download the file some other way.

Best,

### CODE REVIEW

**Comment by LTLA** [comment]
That's fine, but it looks like you deleted the existing Mair reference from the bib file? Also you need to rename the function.

**Comment by sorjuela** [comment]
the Mair reference was repeated. I left the one used in the data.Rmd

**Comment by LTLA** [comment]
Almost there. Is this data for hg19 or hg38? I can't get behind the paywall to look at the paper details.

**Comment by sorjuela** [comment]
This is hg19

**Comment by LTLA** [comment]
Should be available in 2.3.13.

**Pull request merged**
