### PR TITLE
Update metadata

### PR DESCRIPTION
**Pull request by dtm2451**
Used my importDemux function (that doesn't ultimately belong) in dittoSeq to add Sample the minimally 'sometimes meaningful to look at Demuxlet' metadata.  Added age groups.

Also added filtering via cutoffs of the original manuscript too, but perhaps it would be useful to some users if eaither all filtering or just all demuxlet-based filtering steps are left out?  Lemme know.

And check the commit message of second commit too.

### CODE REVIEW

**Comment by LTLA** [comment]
Excellent.

> Used my importDemux function (that doesn't ultimately belong) in dittoSeq

Hm. I wonder where this could go. Maybe **DropletUtils**? Not really droplet-specific, though.

Maybe we should make a `scio` package, for all the miscellaneous reading in/out that people do. I could volunteer `scuttle::readSparseCounts`, and we could create wrappers around **zellkonverter** and **LoomExperiment**. Maybe even auto-detect the format based on the extension... could be nice.

> Also added filtering via cutoffs of the original manuscript too, but perhaps it would be useful to some users if eaither all filtering or just all demuxlet-based filtering steps are left out? Lemme know.

Ideally the end-user would have the option to get all the data. We can either:

1. Save the full count matrix into EHub and then rely on the getter to apply the filtering.
2. Add a `retained` column to `demux` that describes the subset of cells that were retained after filtering. The getter then just filters by this column (default), returns all demux'ed cells (`FALSE`) or the entire dataset including empty droplets (`NA`).

Option 2 is better as I prefer to not have too much extra logic in the yet-to-be-written getter function. 

Also, didn't you have cell type labels floating around somewhere?

**Comment by dtm2451** [comment]
I do.  Had questioned how many things outside of GEO should be added based on a message in slack, but I can update with that later.  Easiest way to do so will be to pull from [figshare](https://figshare.com/articles/dataset/Processed_HSPCs_single-cell_RNA-seq_Seurat_object/11894691) and transfer over the useful metadata.

Extra Qs:
1. Since this is also available via the figshare object, do you think people might be interested in the developmental stage scoring outputs?  (Adds 8 metadata columns for the 4 major cell type annotations - 4 of random forest model outputs `<RFscore_celltype>`, 4 of `inTraining_<celltype>`.)
2. Is it common to given an overview of what metadata mean in the retrieval-function documentation?  I think it'd be warranted for the bits in 1 & also to explain the cell type annotation method (comes from SingleR run in per-cell mode to suggest annotations for cell clusters, then ultimately based on maximal annotations per-cluster, confirmed by trajectory analysis plus some manual curation in which we combined "HSC" + "MPP" into "HSC/MPP").

Side note: All the metadata that I added Friday went into `colData(sce)` but I'd forgotten to update the corresponding line in the final saves.  I'll fix that too when I update!

**Comment by dtm2451** [comment]
Re moving `importDemux` to a final location:
I like these ideas -- a `scio` package + potential support for additional data structures.  The function is universal to Seurat and SCE already so might not be too much work to add more.  Just there's some extra work to be done before this `importDemux()` should go elsewhere... basically I don't think it's ready for the big leagues lol.  Could be improved, but it's not high priority for me right now.

**Comment by dtm2451** [comment]
Removed the trimming code and replaced it with code to pull `retained` via cells kept in the fully processed Seurat object on [figshare](https://figshare.com/articles/dataset/Processed_HSPCs_single-cell_RNA-seq_Seurat_object/11894691), and also `labels`, the final cell type calls, and `DevStageScoring` a DataFrame holding info of similar name.

```
> colnames(colData(sce))
 [1] "Sample"             "demux.doublet.call" "demux.RD.TOTL"      "demux.RD.PASS"      "demux.RD.UNIQ"     
 [6] "demux.N.SNP"        "demux.PRB.DBL"      "age"                "retained"           "labels"            
[11] "DevStageScoring"
```

Ready to go?

**Comment by LTLA** [comment]
I know what I like, and I like what I see. I took the liberty of doing some clean-ups:

- You don't need the weird thing you did with `NAadd`, because you can just subset a DF by absent names and it auto-fills with `NA`s.
- Subsetted down to only the cells with actual statistics when saving, so as to reduce the size of the object that we pull from ExperimentHub. Usually I wouldn't bother but here about 99% of the cells are `NA` so it's worth the effort. We'll just expand it back out to the full 700k cells in the getter function if people request all the cells.
- Added a bunch more diagnostics at every step so that a reader of the compiled HTML can check out what's going on.

> 2\. Is it common to given an overview of what metadata mean in the retrieval-function documentation?  I think it'd be warranted for the bits in 1 & also to explain the cell type annotation method (comes from SingleR run in per-cell mode to suggest annotations for cell clusters, then ultimately based on maximal annotations per-cluster, confirmed by trajectory analysis plus some manual curation in which we combined "HSC" + "MPP" into "HSC/MPP").

It's not common, but that's not because it's a bad idea, just because I don't have the time to do it for the average dataset. Given that you're the author, you can certainly maximize the value of the dataset by describing the annotations in as much detail as necessary. I'll ping you again when the data is up and we can start writing the getter.

**Comment by dtm2451** [comment]
Looks good!

As I made that `NAadd` chunk, I'd figured you'd know a better way.

**Pull request merged**
