### PR TITLE
Spike concs for Paul & Buettner data

### PR DESCRIPTION
**Pull request by Alanocallaghan**

### CODE REVIEW

**Comment by Alanocallaghan** [comment]
I can dig through the papers and add the remaining numbers if you'd prefer to do more in one go. By next week most likely

**Comment by LTLA** [comment]
How many are there? If there's not a lot more, you might as well do it all at once. Don't worry about getting it 100% correct, just give it your best shot and if anyone notices an error, we'll fix it.

Note that `LunSpikeInData` may seem somewhat confusing due to the mixtures (check out the paper), but there should ultimately be the same amount of spike-in added to each well. Can't remember what it was though. Something something 2 uL.

Also add yourself as a contributor to the `DESCRIPTION`.

**Comment by LTLA** [comment]
@Alanocallaghan We should finish this.

**Comment by Alanocallaghan** [comment]
Yeah my bad, I have a stack of reports/presentations atm so github's on the back burner. Will finish this weekend

**Comment by Alanocallaghan** [comment]
Paul data in the current state doesn't have altExp so removed. Also I seem to have blundered the buettner concentrations originally

Which mix people use is seemingly never stated so I'm assuming Mix A throughout.

A couple papers don't seem to mention concentrations at all (colour me surprised). Couldn't find anything on Muraro, Nestorowa.

For your paper I'm going by
> This was done such that each well contained 0.1 µL of a 1:3,000,000 dilution of the ERCC RNA Spike-In Mix (Invitrogen/Thermo Fisher) and 0.12 µL of a 1:3,000,000 dilution of the Spike-in RNA Variant (SIRV) Control Mix E0 (Lexogen).

**Comment by LTLA** [comment]
Looks good. You might want to put some words in the documentation about Segerstolpe's error for one donor.

**Pull request merged**
